export const BASE_URL =
  import.meta.env.VITE_API_BASE_URL || "http://localhost:8001";

export const API_PATH = {
  AUTH: {
    REGISTER: "/api/auth/register",
    SETUP_GRAD_PROFILE: "/api/auth/setup-profile-grad",
    LOGIN: "/api/auth/login",
    GET_PROFILE: "/api/auth/me",
    UPDATE_PROFILE: "/api/users/profile",
    DELETE_ACCOUNT: "/api/users/profile",
    DELETE_RESUME: "/api/users/resume",
    UPLOAD_IMAGE: "/api/auth/upload-image",
    UPLOAD_RESUME: "/api/auth/upload-resume",
    CHECK_EMAIL: "/api/auth/check-email",
    FORGOT_PASSWORD: "/api/auth/forgot-password",
    RESET_PASSWORD: "/api/auth/reset-password",
    CHANGE_PASSWORD: "/api/auth/change-password",
  },
  USERS: {
    GET_PUBLIC_PROFILE: (id) => `/api/users/${id}`,
    GET_ALL_EMPLOYERS: "/api/users/employers",
  },
  DASHBOARD: {
    OVERVIEW: `/api/analytics/overview`,
  },
  JOBS: {
    GET_ALL_JOBS: "/api/jobs",
    GET_RECOMMENDED_JOBS: "/api/jobs/recommended",
    GET_JOB_BY_ID: (id) => `/api/jobs/${id}`,
    POST_JOB: "/api/jobs",
    GET_JOBS_EMPLOYER: "/api/jobs/get-jobs-employer",
    GET_JOB_ID: (id) => `/api/jobs/${id}`,
    UPDATE_JOB: (id) => `/api/jobs/${id}`,
    TOGGLE_CLOSE: (id) => `/api/jobs/${id}/toggle-close`,
    DELETE_JOB: (id) => `/api/jobs/${id}`,
    SAVE_JOB: (id) => `/api/save-jobs/${id}`,
    UNSAVE_JOB: (id) => `/api/save-jobs/${id}`,
    GET_SAVED_JOBS: "/api/save-jobs/my",
  },
  APPLICATIONS: {
    APPLY_TO_JOB: (id) => `/api/applications/${id}`,
    GET_ALL_APPLICATIONS: (id) => `/api/applications/job/${id}`,
    GET_APPLICATION_BY_ID: (id) => `/api/applications/${id}`,
    GET_MY_APPLICATIONS: "/api/applications/my",
    UPDATE_STATUS: (id) => `/api/applications/${id}/status`,
    TERMINATE: (id) => `/api/applications/${id}/terminate`,
    REVIEW_RESIGNATION: (id) => `/api/applications/${id}/resignation-request`,
  },
  IMAGE: { ULOAD_IMAGE: "/api/auth/upload-image" },
  CHAT: {
    GET_CONVERSATIONS: "/api/conversations",
    GET_MESSAGES: (conversationId) => `/api/messages/${conversationId}`,
    SEND_MESSAGE: "/api/messages",
    FIND_OR_CREATE_CONVERSATION: "/api/conversations",
  },
  AI: {
    CHECK_SUITABILITY: "/api/ai/suitability",
    GENERATE_SUMMARY: "/api/ai/summary",
    SCAN_MATCHES: "/api/ai/scan-matches",
    CHECK_CANDIDATE_SUITABILITY: "/api/ai/candidate-suitability",
    SUBMIT_FEEDBACK: "/api/ai/feedback",
  },
  NOTIFICATIONS: {
    GET_ALL: "/api/notifications",
    MARK_READ: (id) => `/api/notifications/${id}/read`,
    MARK_ALL_READ: "/api/notifications/read-all",
    PUSH_SUBSCRIBE: "/api/notifications/push-subscribe",
  },

  ADMIN: {
    UPLOAD: "/api/admin/upload",
    ANALYTICS: "/api/admin/analytics",
    USERS: "/api/admin/users",
    CREATE_USER: "/api/admin/users",
    JOBS: "/api/admin/jobs",
    CREATE_JOB: "/api/admin/jobs",
    APPLICATIONS: "/api/admin/applications",
    DELETE_APPLICATION: (id) => `/api/admin/applications/${id}`,
    REPORTS: "/api/admin/reports",
    FAQS: "/api/admin/faqs",
    JOB_FAQS: "/api/admin/job-faqs",
    CREATE_JOB_FAQ: "/api/admin/job-faqs",
    UPDATE_JOB_FAQ: (id) => `/api/admin/job-faqs/${id}`,
    DELETE_JOB_FAQ: (id) => `/api/admin/job-faqs/${id}`,
    EMPLOYER_SETTINGS: "/api/admin/employer-settings",
    DELETE_USER: (id) => `/api/admin/users/${id}`,
    UPDATE_USER: (id) => `/api/admin/users/${id}`,
    USER_SAVED_JOBS: (id) => `/api/admin/users/${id}/saved-jobs`,
    DELETE_JOB: (id) => `/api/admin/jobs/${id}`,
    UPDATE_JOB: (id) => `/api/admin/jobs/${id}`,
    CREATE_FAQ: "/api/admin/faqs",
    UPDATE_FAQ: (id) => `/api/admin/faqs/${id}`,
    DELETE_FAQ: (id) => `/api/admin/faqs/${id}`,
    CREATE_EMPLOYER_SETTINGS: "/api/admin/employer-settings",
    UPDATE_EMPLOYER_SETTINGS: (id) => `/api/admin/employer-settings/${id}`,
    ASSESSMENTS_REVIEWS: "api/assessments/submissions/review",
    ASSESSMENTS_REVIEWS_ID: (id) => `/api/assessments/submissions/${id}`,
    AI_FEEDBACKS: "/api/admin/ai-feedback",
    DELETE_AI_FEEDBACK: (id) => `/api/admin/ai-feedback/${id}`,
  },
  EMPLOYER: {
    SETTINGS: "/api/employer/settings",
    FAQS: "/api/employer/faqs",
    FAQ_ID: (id) => `/api/employer/faqs/${id}`,
    GET_PUBLIC_FAQS: (employerId) => `/api/employer/${employerId}/public-faqs`,
  },
  INTERVIEW: {
    GET_ROLES: "/api/interview-roles",
    GET_ALL_QUESTIONS: "/api/interview-roles/all-questions",
    GET_ROLE_BY_ID: (id) => `/api/interview-roles/${id}`,
    MANAGE_QUESTIONS: (roleId) => `/api/interview-roles/${roleId}/questions`,
    MANAGE_QUESTION_BY_ID: (roleId, questionId) =>
      `/api/interview-roles/${roleId}/questions/${questionId}`,
    EVALUATE: "/api/interviews/evaluate",
    GET_USER_INTERVIEWS: "/api/interviews/user",
    GET_GRADUATE_INTERVIEWS: (userId) => `/api/interviews/graduate/${userId}`,
    GET_ALL_SCORES: "/api/interviews/all-scores",
    GET_INTERVIEW_BY_ID: (id) => `/api/interviews/${id}`,
    DELETE_INTERVIEW: (id) => `/api/interviews/${id}`,
  },
  TERMINATION_REVIEWS: {
    GET_REASONS: "/api/termination-reviews/reasons",
    CREATE_REASON: "/api/termination-reviews/reasons",
    UPDATE_REASON: (id) => `/api/termination-reviews/reasons/${id}`,
    DELETE_REASON: (id) => `/api/termination-reviews/reasons/${id}`,
    TERMINATE: "/api/termination-reviews/terminate",
    EMPLOYER_RATE: (id) => `/api/termination-reviews/${id}/employer-rate`,
    EMPLOYEE_REVIEWS: (userId) => `/api/termination-reviews/employee/${userId}/reviews`,
    JOBSEEKER_RATE: (id) => `/api/termination-reviews/${id}/jobseeker-rate`,
    DISMISS_PROMPT: (id) => `/api/termination-reviews/${id}/dismiss`,
    MY_PENDING: "/api/termination-reviews/my-pending",
    JOB_REVIEWS: (jobId) => `/api/termination-reviews/job/${jobId}`,
    COMPANY_REVIEWS: (companyId) => `/api/termination-reviews/company/${companyId}`,
    EMPLOYEE_SCORE: (userId) => `/api/termination-reviews/employee/${userId}/score`,
  },
  CONTRACTS: {
    CREATE: "/api/contracts",
    GET_ALL: "/api/contracts",
    GET_BY_ID: (id) => `/api/contracts/${id}`,
    UPDATE_STATUS: (id) => `/api/contracts/${id}/status`,
    EXTEND: (id) => `/api/contracts/${id}/extend`,
    GET_BY_EMPLOYEE: (employeeId) => `/api/contracts?employee=${employeeId}`,
  },
  EMPLOYER_ANALYTICS: {
    APPLICATIONS_OVER_TIME: "/api/analytics/employer/applications-over-time",
    TOP_JOBS: "/api/analytics/employer/top-jobs",
    RETENTION: "/api/analytics/employer/retention",
    TERMINATION_REASONS: "/api/analytics/employer/termination-reasons",
    SKILL_GAPS: "/api/analytics/employer/skill-gaps",
    AI_SUMMARY: "/api/analytics/employer/ai-summary",
  },
};